### ISSUE TITLE
MathLine & knitr?

### ISSUE THREAD

**Issue by bjornerstedt** [rljacobson/MathLine#1]
It would be interesting if MathLine could be used for Mathematica integration with knitr as described in [knitr](http://yihui.name/knitr/demo/engines/). With knitr integration either R markdown or LyX could be used as front ends for Mathematica.

**Comment by rljacobson** [comment]
Your comment is the first I've heard of knitr, but it looks interesting. What MathLine does is just replace Mathematica's command line front end with a functionally identical command line front end. The reason this is useful is that Mathematica's official front end is a moving target, and changes from version to version to the official front end can break interoperability between Mathematica and third party software. On the other hand, version changes do not effect the behavior of MathLine, so MathLine can be relied upon by third party developers. I don't see why knitr couldn't take advantage of this.
